### ISSUE TITLE
Basic high level visualizations

### ISSUE THREAD

**Issue by bradenwatkins** [Career-Launchpad/client#101]

**Comment by justintunev7** [comment]
1. Research packages for visualizations
2. Implement with salary distributions (test run)
3. Other graphs: salaries by major, salaries by company, number of offers given to students by major, etc.
4. (stretch) Allow frontend configuration of graphs

**Comment by justintunev7** [comment]
Some options for packages:

D3: https://observablehq.com/@d3/gallery
