### ISSUE TITLE
Change all type selectors to combo boxes

### ISSUE THREAD

**Issue by tylermercer** [Career-Launchpad/client#54]
I've noticed that the type selectors (e.g. for position type, wage type, etc) are not very usable because you can't type in them, you have to bring up the menu and select one.

I think we should use a Combo Box instead: https://material-ui.com/components/autocomplete/#combo-box

**Comment by bradenwatkins** [comment]
- Change all selectors to combo boxes on the frontend
- Implement necessary resolvers on the backend
